export { default as NotFoundCom } from './NotFoundCom'
export { default as Frame } from './Frame'
export { default as WriteMyBlog } from './WriteMyBlog'
export { default as Box } from './Box'
export { default as AlertCom } from './AlertCom'
export { default as SpinCom } from './SpinCom'